### PR TITLE
Added action.yml and pack.sh

### PR DESCRIPTION
**Pull request by jkutner**
This Github Action adds several tools needed to work with Pack and Buildpacks, including:
- `pack`
- `jq`
- `yj`
- `crane`

Github only allows one `action.yml` per repo, so we might want to move this to a `setup-pack` repo. That way we could add other actions later on.

Minimal usage of this would look like:

```yaml
name: Buildpackage
on:
    release:
        types:
            - published
jobs:
    create-package:
        name: Create Package
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v2
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to GitHub Package Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GHCR_TOKEN }}
            - id: pack
              name: Setup Pack CLI
              uses: buildpacks/github-actions/setup-pack
              with:
                version: "0.14.1"
            - id: package
              name: Package Buildpack
              run: |
                #!/usr/bin/env bash
                set -euo pipefail

                VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
                pack package-buildpack --config package.toml --publish ${PACKAGE}:${VERSION}
              shell: bash
              env:
                PACKAGE: ghcr.io/${{ github.repository_owner }}/buildpacks/jkutner_minecraft
```

If a user wants to chain this together with the registry action, they would do something like:

```yaml
jobs:
// ...
            - id: package
              name: Package Buildpack
              run: |
                #!/usr/bin/env bash
                set -euo pipefail

                VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
                pack package-buildpack --config package.toml --publish ${PACKAGE}:${VERSION}
                DIGEST="$(crane digest ${PACKAGE}:${VERSION})"

                echo "::set-output name=version::$VERSION"
                echo "::set-output name=digest::$DIGEST"
              shell: bash
              env:
                PACKAGE: ghcr.io/${{ github.repository_owner }}/buildpacks/jkutner_minecraft
            - id: register
              name: Register Buildpack
              uses: docker://ghcr.io/buildpacks/actions/registry:main
              with:
                token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
                id:      jkutner/minecraft
                version: ${{ steps.package.outputs.version }}
                address: ghcr.io/jkutner/buildpacks/minecraft@${{ steps.package.outputs.digest }}

### CODE REVIEW

**Review by nebhale — CHANGES_REQUESTED** [review]
Docs please 😇

**Comment by nebhale** [comment]
Also, while I understand the need for a "Setup Pack CLI" kind of action (and would approve an action with that name moved down a level) wouldn't users be well served, by a more complete solution?

```yaml
steps:
- id: checkout
  name: Checkout code
  uses: actions/checkout@v2
- if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
  name: Login to GitHub Package Registry
  uses: docker/login-action@v1
  with:
    registry: ghcr.io
    username: ${{ github.repository_owner }}
    password: ${{ secrets.GHCR_TOKEN }}
- id:   info
  uses: ghcr.io/buildpacks/actions/buildpack-info
- id:   package
  uses: ghcr.io/buildpacks/actions/package-buildpack
  with:
    pack_version:  "0.14.1"      # Optional override of baked in version
    configuration: package.toml  # Optional defaulting to local pack.toml if it exists, or synthesized one-liner if it doesn't
    package:       ghcr.io/${{ github.repository_owner }}/buildpacks/jkutner_minecraft:${{ steps.info.outputs.version }}
    publish:       true
- uses: docker://ghcr.io/buildpacks/actions/registry:main
  with:
    token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
    id:      jkutner/minecraft
    version: ${{ steps.info.outputs.version }}
    address: ghcr.io/${{ github.repository_owner }}/buildpacks/minecraft@${{ steps.package.outputs.digest }}
```

**Comment by jkutner** [comment]
@nebhale that's the route I went originally: https://github.com/buildpacks/github-actions/pull/2

However, I don't think it won't work unless you do both:
- pass your GHCR token into `ghcr.io/buildpacks/actions/package-buildpack`
- have `ghcr.io/buildpacks/actions/package-buildpack` do all the docker login steps

When I was testing it out, I could get the `docker/login-action@v1` setup to carry over.

If we can get that to work, I would definitely prefer it.

**Comment by nebhale** [comment]
Interesting.  I agree that we shouldn't ask for the credentials and this is suitable if we can't get login to work across multiple steps.  Let me experiment.

**Comment by nebhale** [comment]
Well crap.  I've had three different goes at this, and there's just no way around it.  I believe that the restriction is, regardless of what _style_ of action you create, none of them have access to the job's work directory except to write _new_ things to it.  I kind of understand the security of it, but its certainly makes composition of actions difficult.  I'll review this in the context of  a `setup-pack` action.

**Comment by jkutner** [comment]
@nebhale bummer. but it's nice that it's in `setup-pack/` (i didn't realize you could do that). All things considered, I think this is good. Thanks for refactoring and adding docs.

**Review by nebhale — APPROVED** [review]

**Pull request merged**
